# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a3f35dd315f1212a5b3e2f317c276d0d7e9d45fe9e440f34e4114044054fbf2f3b4a3b4ba9391d3cb32e769e2ba4061b166584467431a12565c271afd440f7e

test:
  secret_key_base: fd046989810feb6c943b527052f8406bf41557e1230ab28e6db74692f5047bdfa4e2cd90ab0ba5d11e45f14969b093e056f8c78c9987b19abb000069fece05f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
